"""add_scheduler_tables_clean

Revision ID: 2694c7b3f8bf
Revises: f10171a1c45b
Create Date: 2026-01-28 23:47:00.299012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2694c7b3f8bf'
down_revision: Union[str, Sequence[str], None] = 'f10171a1c45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_schedules',
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('cron_expression', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('bot_name')
    )
    op.create_table('bot_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('log_output', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['bot_name'], ['bot_schedules.bot_name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_symbol_time'), table_name='market_data_cache', schema='common')
    op.drop_index(op.f('market_data_cache_timestamp_idx'), table_name='market_data_cache', schema='common')
    op.add_column('trade_signals', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True), schema='common')
    op.add_column('trade_signals', sa.Column('score', sa.Float(), nullable=True), schema='common')
    op.add_column('trade_signals', sa.Column('is_favorite', sa.Boolean(), nullable=True), schema='common')
    op.add_column('trade_signals', sa.Column('is_archived', sa.Boolean(), nullable=True), schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade_signals', 'is_archived', schema='common')
    op.drop_column('trade_signals', 'is_favorite', schema='common')
    op.drop_column('trade_signals', 'score', schema='common')
    op.drop_column('trade_signals', 'updated_at', schema='common')
    op.create_index(op.f('market_data_cache_timestamp_idx'), 'market_data_cache', [sa.literal_column('timestamp DESC')], unique=False, schema='common')
    op.create_index(op.f('ix_symbol_time'), 'market_data_cache', ['instrument_id', sa.literal_column('timestamp DESC')], unique=False, schema='common')
    op.drop_table('bot_executions')
    op.drop_table('bot_schedules')
    # ### end Alembic commands ###
