"""empty message

Revision ID: 27dc7a2b5d61
Revises: 2694c7b3f8bf
Create Date: 2026-01-30 23:20:53.610611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '27dc7a2b5d61'
down_revision: Union[str, Sequence[str], None] = '2694c7b3f8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_states', schema='common')
    op.alter_column('system_logs', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               schema='common')
    op.alter_column('system_logs', 'level',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=20),
               existing_nullable=True,
               schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_logs', 'level',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=10),
               existing_nullable=True,
               schema='common')
    op.alter_column('system_logs', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               schema='common')
    op.create_table('bot_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('last_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('next_run_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('info_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('config', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_auto_run', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('run_interval_mins', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('run_at_time', sa.VARCHAR(length=5), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('bot_states_pkey')),
    sa.UniqueConstraint('name', name=op.f('bot_states_name_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='common'
    )
    # ### end Alembic commands ###
