"""Add institutional and cash flow fields

Revision ID: 68f3f4123f4d
Revises: e08af79cad9e
Create Date: 2026-04-13 21:05:21.645493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68f3f4123f4d'
down_revision: Union[str, Sequence[str], None] = 'e08af79cad9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_cache', sa.Column('inst_ownership', sa.Float(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('inst_count', sa.Integer(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('operating_cash_flow', sa.BigInteger(), nullable=True), schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_cache', 'operating_cash_flow', schema='common')
    op.drop_column('fundamental_cache', 'inst_count', schema='common')
    op.drop_column('fundamental_cache', 'inst_ownership', schema='common')
    # ### end Alembic commands ###
