"""add_exchange_calendar_table

Revision ID: 79780e9539f7
Revises: c65b5f6f252f
Create Date: 2026-02-15 22:56:41.574617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79780e9539f7'
down_revision: Union[str, Sequence[str], None] = 'c65b5f6f252f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchange_calendar',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=True),
    sa.Column('close_time', sa.Time(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_index(op.f('ix_common_exchange_calendar_date'), 'exchange_calendar', ['date'], unique=False, schema='common')
    op.create_index(op.f('ix_common_exchange_calendar_exchange'), 'exchange_calendar', ['exchange'], unique=False, schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_common_exchange_calendar_exchange'), table_name='exchange_calendar', schema='common')
    op.drop_index(op.f('ix_common_exchange_calendar_date'), table_name='exchange_calendar', schema='common')
    op.drop_table('exchange_calendar', schema='common')
    # ### end Alembic commands ###
