"""empty message

Revision ID: 934b4808e768
Revises: 27dc7a2b5d61
Create Date: 2026-02-01 01:18:35.059500

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '934b4808e768'
down_revision: Union[str, Sequence[str], None] = '27dc7a2b5d61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('vix', sa.Float(), nullable=True),
    sa.Column('us10y', sa.Float(), nullable=True),
    sa.Column('dxy', sa.Float(), nullable=True),
    sa.Column('put_call_ratio', sa.Float(), nullable=True),
    sa.Column('spx', sa.Float(), nullable=True),
    sa.Column('ndx', sa.Float(), nullable=True),
    sa.Column('dax', sa.Float(), nullable=True),
    sa.Column('btc_usd', sa.Float(), nullable=True),
    sa.Column('xau_usd', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('sentiment_label', sa.String(length=50), nullable=True),
    sa.Column('is_trading_allowed', sa.Boolean(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('market_sentiment', schema='common')
    # ### end Alembic commands ###
