"""first_clean_migration

Revision ID: 9a057eeb5700
Revises: 
Create Date: 2026-01-08 20:29:11.654804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a057eeb5700'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('con_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('sector', sa.String(length=150), nullable=True),
    sa.Column('industry', sa.String(length=150), nullable=True),
    sa.Column('data_role', sa.String(length=50), nullable=True),
    sa.Column('sec_type', sa.String(length=10), nullable=True),
    sa.Column('currency', sa.String(length=5), nullable=True),
    sa.Column('exchange', sa.String(length=20), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('con_id'),
    sa.UniqueConstraint('symbol'),
    schema='common'
    )
    op.create_table('system_logs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('level', sa.String(length=10), nullable=True),
    sa.Column('module', sa.String(length=50), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ib_order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=4), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('lmt_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='live'
    )
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ib_order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=4), nullable=True),
    sa.Column('total_quantity', sa.Float(), nullable=True),
    sa.Column('order_type', sa.String(length=10), nullable=True),
    sa.Column('lmt_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='paper'
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('position', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='paper'
    )
    op.create_table('fundamental_cache',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('peg_ratio', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.BigInteger(), nullable=True),
    sa.Column('div_yield', sa.Float(), nullable=True),
    sa.Column('price_to_book', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('recommendation_mean', sa.Float(), nullable=True),
    sa.Column('current_iv', sa.Float(), nullable=True),
    sa.Column('iv_rank', sa.Float(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['common.instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_index(op.f('ix_common_fundamental_cache_id'), 'fundamental_cache', ['id'], unique=False, schema='common')
    op.create_table('market_data_cache',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('timeframe', sa.String(length=10), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('ma_50', sa.Float(), nullable=True),
    sa.Column('ma_200', sa.Float(), nullable=True),
    sa.Column('rsi_14', sa.Float(), nullable=True),
    sa.Column('daily_return', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['common.instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'timestamp', 'timeframe'),
    schema='common'
    )
    op.create_table('trade_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('bot_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('signal_price', sa.Float(), nullable=True),
    sa.Column('support_level', sa.Float(), nullable=True),
    sa.Column('resistance_level', sa.Float(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('signal_data', sa.JSON(), nullable=True),
    sa.Column('buy_price', sa.Float(), nullable=True),
    sa.Column('sell_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['common.instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    op.create_table('watchlist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=100), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['common.instruments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist', schema='common')
    op.drop_table('trade_signals', schema='common')
    op.drop_table('market_data_cache', schema='common')
    op.drop_index(op.f('ix_common_fundamental_cache_id'), table_name='fundamental_cache', schema='common')
    op.drop_table('fundamental_cache', schema='common')
    op.drop_table('positions', schema='paper')
    op.drop_table('orders', schema='paper')
    op.drop_table('positions', schema='live')
    op.drop_table('orders', schema='live')
    op.drop_table('system_logs', schema='common')
    op.drop_table('instruments', schema='common')
    # ### end Alembic commands ###
