"""Add is_active to PremiumWatchlist

Revision ID: 9ddbf618ddbd
Revises: 1fed804fbcec
Create Date: 2026-02-22 15:18:26.896313

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ddbf618ddbd'
down_revision: Union[str, Sequence[str], None] = '1fed804fbcec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('premium_watchlist', sa.Column('is_active', sa.Boolean(), nullable=True), schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('premium_watchlist', 'is_active', schema='common')
    # ### end Alembic commands ###
