"""add_notifications_table

Revision ID: c65b5f6f252f
Revises: 934b4808e768
Create Date: 2026-02-15 17:07:58.322925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c65b5f6f252f'
down_revision: Union[str, Sequence[str], None] = '934b4808e768'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.Enum('TELEGRAM', 'TWITTER', name='notificationchannel'), nullable=False),
    sa.Column('scope', sa.Enum('PUBLIC', 'PRIVATE', name='notificationscope'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SENT', 'FAILED', 'SKIPPED', name='notificationstatus'), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='common'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications', schema='common')
    # ### end Alembic commands ###
