"""Add new fundamental metrics

Revision ID: e08af79cad9e
Revises: f53d92dbd054
Create Date: 2026-03-28 16:39:33.758161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e08af79cad9e'
down_revision: Union[str, Sequence[str], None] = 'f53d92dbd054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_cache', sa.Column('debt_to_equity', sa.Float(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('revenue_growth', sa.Float(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('price_to_sales', sa.Float(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('gross_margin', sa.Float(), nullable=True), schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_cache', 'gross_margin', schema='common')
    op.drop_column('fundamental_cache', 'price_to_sales', schema='common')
    op.drop_column('fundamental_cache', 'revenue_growth', schema='common')
    op.drop_column('fundamental_cache', 'debt_to_equity', schema='common')
    # ### end Alembic commands ###
