"""add_roic_and_fundamental_scores

Revision ID: f53d92dbd054
Revises: 9ddbf618ddbd
Create Date: 2026-03-28 13:43:21.261766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f53d92dbd054'
down_revision: Union[str, Sequence[str], None] = '9ddbf618ddbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_cache', sa.Column('roic', sa.Float(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('fundamental_score', sa.Float(), nullable=True), schema='common')
    op.add_column('fundamental_cache', sa.Column('score_breakdown', sa.JSON(), nullable=True), schema='common')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_cache', 'score_breakdown', schema='common')
    op.drop_column('fundamental_cache', 'fundamental_score', schema='common')
    op.drop_column('fundamental_cache', 'roic', schema='common')
    # ### end Alembic commands ###
