"""initial_schema

Revision ID: f67e81985a3c
Revises: 
Create Date: 2025-12-16 01:35:01.961174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f67e81985a3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist', schema='common')
    op.drop_table('market_data_cache', schema='common')
    op.drop_table('fundamental_cache', schema='common')
    op.drop_table('positions', schema='paper')
    op.drop_table('orders', schema='paper')
    op.drop_table('positions', schema='live')
    op.drop_table('orders', schema='live')
    op.drop_table('system_logs', schema='common')
    op.drop_table('instruments', schema='common')
    # ### end Alembic commands ###