[tool.poetry]
name = "metrix-backend"
version = "0.1.0"
description = "Financial Backend"
authors = ["Hurkan"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.128.0"
uvicorn = {extras = ["standard"], version = "^0.40.0"}
sqlalchemy = "^2.0.45"
asyncpg = "^0.31.0"
psycopg2-binary = "^2.9.11"
alembic = "^1.17.2"
pydantic-settings = "^2.12.0"
python-dotenv = "^1.2.1"
ib-async = "^2.1.0"
pandas = "^2.3.3"
yfinance = "^1.0"
firebase-admin = "^7.1.0"
aiohttp = "^3.13.3"
apscheduler = "^3.11.2"
nest-asyncio = "^1.6.0"

[tool.taskipy.tasks]
dev = "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --loop asyncio"
prod = "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio"
migrate = "alembic revision --autogenerate"

[tool.poetry.group.dev.dependencies]
taskipy = "^1.14.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"